// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2xy11CMu50gDJOqxz7IHelNaqtzI1TY',
    appId: '1:816593628632:web:302ef83d1e709ed1cb56ad',
    messagingSenderId: '816593628632',
    projectId: 'ncatch-ef4cf',
    authDomain: 'ncatch-ef4cf.firebaseapp.com',
    storageBucket: 'ncatch-ef4cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAzmggRRBBvwAx-0pN-pB86mmopfjAHU',
    appId: '1:816593628632:android:6fbdf8d0b795e904cb56ad',
    messagingSenderId: '816593628632',
    projectId: 'ncatch-ef4cf',
    storageBucket: 'ncatch-ef4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN9p-i5D84JzqSnRphmzOxFzBWvblb3ho',
    appId: '1:816593628632:ios:14620acb4c43f266cb56ad',
    messagingSenderId: '816593628632',
    projectId: 'ncatch-ef4cf',
    storageBucket: 'ncatch-ef4cf.appspot.com',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN9p-i5D84JzqSnRphmzOxFzBWvblb3ho',
    appId: '1:816593628632:ios:39954e98678d4f93cb56ad',
    messagingSenderId: '816593628632',
    projectId: 'ncatch-ef4cf',
    storageBucket: 'ncatch-ef4cf.appspot.com',
    iosBundleId: 'com.example.flutterApplication9.RunnerTests',
  );
}
